### PR TITLE
Fix generated ocall wrapper to return the correct status

### LINKED ISSUE #1165: oeedger8r: ocall returns OE_OUT_OF_MEMORY instead of OE_ENCLAVE_ABORTING
Making an ocall from an enclave which is aborting returns OE_OUT_OF_MEMORY instead of OE_ENCLAVE_ABORTING.
This affects abortStatus test and workaround was added to PASS this test on Linux

This error is in the code generated by the oeedger8r.

### PR DESCRIPTION
**Pull request by andschwa**
This resolves #1165.

### CODE REVIEW

**Comment by andschwa** [comment]
bors try

File: tools/oeedger8r/Emitter.ml [hunk 1]
```diff
@@ -683,6 +683,10 @@ let oe_gen_ocall_enclave_wrapper (os:out_channel) (uf:Ast.untrusted_func) =
   fprintf os "\n";
   fprintf os "{\n";
   fprintf os "    oe_result_t _result = OE_FAILURE;\n\n";
+  fprintf os "    /* If the enclave is in crashing/crashed status, new OCALL should fail\n";
```
Comment (andschwa) [inline tools/oeedger8r/Emitter.ml]: This logic is similar to the [old implementation](https://github.com/Microsoft/openenclave/blob/e504559e9ea03dfd25f8b2f58a96b12c9c140e48/enclave/core/sgx/calls.c#L548).

**Comment by andschwa** [comment]
Only failures looked like flakiness:

```
The following tests FAILED:
	 82 - tests/ocall-create (Failed)
	 84 - tests/SampleApp (Failed)
	 85 - tests/SampleAppCRT (Failed)
```

It was on just one Windows node, in the debug configuration. The release configuration passed.

File: include/openenclave/edger8r/enclave.h [hunk 2]
```diff
@@ -34,6 +34,13 @@ typedef void (*oe_ecall_func_t)(
     size_t output_buffer_size,
     size_t* output_bytes_written);
 
+/**
+ * Get the internal status of the enclave.
+ *
+ * @returns read-only copy of the internal status.
+ */
+oe_result_t oe_get_enclave_status();
```
Comment (anakrish) [inline include/openenclave/edger8r/enclave.h]: This looks good. Can you make this a no-op for non-sgx similar to oe_lfence?

Comment (andschwa) [reply include/openenclave/edger8r/enclave.h]: Ah! Good catch.

File: tools/oeedger8r/Emitter.ml [hunk 3]
```diff
@@ -683,6 +683,10 @@ let oe_gen_ocall_enclave_wrapper (os:out_channel) (uf:Ast.untrusted_func) =
...
+  fprintf os "       immediately. */\n";
+  fprintf os "    if (oe_get_enclave_status() != OE_OK)\n";
```
Comment (EMumau) [inline tools/oeedger8r/Emitter.ml]: Because this code "functioned correctly" but returned the wrong error code prior to this fix, should this status test be moved to the failure case of oe_call_host_function (line 712).  Doing so would be an optimization as this test would only be called when a failure had occurred.

Comment (andschwa) [reply tools/oeedger8r/Emitter.ml]: That wouldn't work. This test was returning OOM because the generated code immediately after this makes an ocall to allocate buffers. It is that ocall that fails, because _it_ sees the enclave is aborting. However, its interface, mirroring malloc, is very poor and only returns NULL as failure, thus swallowing the information that the error was due to the enclave aborting, not OOM.

**Comment by andschwa** [comment]
bors try

File: tools/oeedger8r/Emitter.ml (hunk 3 above)
Comment (andschwa) [reply tools/oeedger8r/Emitter.ml]: Ah, we talked offline and my understanding is that you're suggesting to optimize this by moving the comparison to where the ocall to malloc has returned NULL (to check if it was indeed an OOM or because the enclave was aborting). While reasonable, it's inconsistent with the oe_ocall implementation. We can and maybe should do this, but we should do it separately so we can optimize both implementations.

**Comment by andschwa** [comment]
Bors try actually passed, but one machine timed out before it even started the build. /shrug

File: tools/oeedger8r/Emitter.ml (hunk 3 above)
Comment (anakrish) [reply tools/oeedger8r/Emitter.ml]: I am fine with this implementation since it mirrors the strategy in oe_ocall where the check was always performed:
https://github.com/Microsoft/openenclave/blob/master/enclave/core/sgx/calls.c#L548

I would be up for optimizations - say we could avoid doing the host malloc if there are no arguments or for a small sized argument etc. But we can do optimizations in another pass.

File: include/openenclave/edger8r/enclave.h [hunk 4]
```diff
@@ -100,6 +100,20 @@ void oe_free_ocall_buffer(void* buffer);
...
 
+#if __x86_64__ || _M_X64
+/**
+ * Get the internal status of the enclave.
+ *
+ * @returns read-only copy of the internal status.
+ */
+oe_result_t oe_get_enclave_status();
+#else // Make oe_get_enclave_status a no-op for non x86-64 platforms.
+inline oe_result_t oe_get_enclave_status()
```
Comment (anakrish) [inline include/openenclave/edger8r/enclave.h]: Better to use OE_INLINE which is supported to handle different compilers and C standards.

Comment (andschwa) [reply include/openenclave/edger8r/enclave.h]: Didn't even know it existed.
