### PR TITLE
Fix #990: Clarify or change result of oe_create_enclave if initialization fails

### LINKED ISSUE #990: Clarify or change result of oe_create_enclave if initialization fails
If I have code such as the following within an enclave (at top level):
```
class Foo {
public:
  Foo() { throw std::runtime_error("Ooops"); }
};

Foo f;
```
Then oe_create_enclave returns success, despite oe_abort having been called (via std::terminate) from the user's initialization code. The failure to initialize is only detected during subsequent attempts to make call-ins, none of which even reach the user code but instead return OE_ENCLAVE_ABORTING. This seems surprising.
[init_abort.zip](https://github.com/Microsoft/openenclave/files/2525441/init_abort.zip)

### PR DESCRIPTION
**Pull request by berinpaul**
The `arg_out` output parameter is not checked in the enclave initialisation ecall. As a result the failure to initialise is detected only in subsequent ecall, where the `arg_out` parameter is checked. Added `OE_CHECK` for `arg_out` for the `OE_ECALL_INIT_ENCLAVE` ecall.

### CODE REVIEW

**Comment by CodeMonkeyLeet** [comment]
This is a good fix, but does this actually address the issue in #990? If global initialization functions are invoked as part of `oe_call_init_functions` then that is still a `void` return function that depends on thrown exceptions to indicate failure.

@berinpaul please write a repro test under tests/stdcxx and verify that #990 is addressed.

File: tests/stdcxx/enc/init_chk.cpp [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
[the remark this answers is not in the document]
Comment (berinpaul) [reply tests/stdcxx/enc/init_chk.cpp]: source file renamed

File: tests/stdcxx/host/host.cpp [hunk 2]
```diff
@@ -53,17 +53,28 @@ int main(int argc, const char* argv[])
              0,
              &enclave)) != OE_OK)
     {
+        if (result == OE_ENCLAVE_ABORTING)
+        {
+            printf(
+                "=== Passed: enclave not created, enclave status: (%s)\n",
+                oe_result_str(result));
+            goto done;
```
[the remark this answers is not in the document]
Comment (berinpaul) [reply tests/stdcxx/host/host.cpp]: Additional arguments added for test

**Comment by berinpaul** [comment]
bors try

File: tests/stdcxx/enc/global_init_exception.cpp [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+/* This test is to check that oe_create_enclave does not return success
+   when enclave initialisation fails */
+
+class Foo
+{
+  public:
+    Foo()
+    {
+        throw std::runtime_error("Ooops");
```
Comment (anitagov) [inline tests/stdcxx/enc/global_init_exception.cpp]: Typo: Ooops is spelt as oops. But a better message should be thrown.

**Comment by berinpaul** [comment]
bors try

**Comment by berinpaul** [comment]
bors try

File: tests/stdcxx/host/host.cpp [hunk 4]
```diff
@@ -35,35 +35,47 @@ int main(int argc, const char* argv[])
     oe_result_t result;
     oe_enclave_t* enclave = NULL;
 
-    if (argc != 2)
+    if (argc != 3)
     {
         fprintf(stderr, "Usage: %s ENCLAVE\n", argv[0]);
```
Comment (anakrish) [inline tests/stdcxx/host/host.cpp]: Update the Usage message to include the 3rd argument.

File: tests/stdcxx/host/host.cpp [hunk 5]
```diff
@@ -35,35 +35,47 @@ int main(int argc, const char* argv[])
...
     {
-        oe_put_err("oe_terminate_enclave(): result=%u", result);
+        if (strcmp(oe_result_str(result), argv[2]) == 0)
+        {
+            TestStdcxx(enclave);
+            printf("=== passed all tests (%s)\n", argv[0]);
+            goto done;
+        }
+        oe_put_err("oe_create_enclave(): result=%u", result);
     }
```
Comment (anakrish) [inline tests/stdcxx/host/host.cpp]: also add a case and fail the test if an invalid 3rd argument is passed.

Comment (berinpaul) [reply tests/stdcxx/host/host.cpp]: Case added
