### PR TITLE
Wnd memory management in simulated enclaves

### LINKED ISSUE #636: Incorrect memory management in Windows simulated enclaves.
To get an enclave address aligned to the enclave size, the Windows code for simulation imitates the Linux code by allocating twice the enclave size, performing the alignment and then unmapping the unused regions with `MEM_DECOMMIT`.  

During this alignment process, we keep the aligned pointer and throw away the pointer from `VirtualAlloc`. As a result, we can't actually free the pages during Enclave deletion using `MEM_RELEASE`.

We can probably just remove the power of two alignment process and just having a page aligned page as mentioned in Simon's comment (https://github.com/Microsoft/openenclave/pull/610#discussion_r215078199 ).

### PR DESCRIPTION
**Pull request by sushantstripathi**
Fixes #636

### CODE REVIEW

**Comment by sushantstripathi** [comment]
bors try

File: host/sgxload.c [hunk 1]
```diff
@@ -781,27 +746,24 @@ oe_result_t oe_sgx_delete_enclave(oe_enclave_t* enclave)
     }
     else /* FLC simulation mode needs to munmap. */
 #endif
+
+#endif /* END __LINUX __*/
     {
-        /* Non-FLC Linux and simulation mode both allocate memory. */
-        munmap((void*)enclave->addr, enclave->size);
+        /* free allocate memory. */
+        result = _sgx_free_enclave_memory((void*)enclave->addr, enclave->size);
```
Comment (CodeMonkeyLeet) [inline host/sgxload.c]: This is an incorrect refactor; the point of creating `_sgx_free_enclave_memory` is to consolidate all of the different deallocation build logic into a single function, not that `_sgx_free_enclave_memory` replaces `munmap` directly. i.e. lines 772-800 should be the implementation of `_sgx_free_enclave_memory` (except that line 796 replaces all of 790-799)

This is also likely what is causing tests to fail in the SGX1FLC configuration in your CI runs.

**Comment by sushantstripathi** [comment]
bors try

**Comment by sushantstripathi** [comment]
bors try

File: host/sgxload.c [hunk 2]
```diff
@@ -767,41 +732,47 @@ oe_result_t oe_sgx_delete_enclave(oe_enclave_t* enclave)
...
-     * flag. We can't do this for simulation mode because `MEM_RELEASE`
-     * requires `enclave->addr` to be the same one returned by `VirtualAlloc`,
-     * which is often not the case due to the enclave address alignment
-     * requirements. We use `MEM_DECOMMIT` instead. */
-    if (!enclave->simulate)
-        VirtualFree((void*)enclave->addr, 0, MEM_RELEASE);
-    else
-        VirtualFree((void*)enclave->addr, enclave->size, MEM_DECOMMIT);
-
+    VirtualFree(enclave, 0, MEM_RELEASE);
```
Comment (CodeMonkeyLeet) [inline host/sgxload.c]: How does this work? You're unmapping/freeing `enclave` instead `enclave->addr`

File: host/sgxload.c [hunk 3]
```diff
@@ -767,41 +732,47 @@ oe_result_t oe_sgx_delete_enclave(oe_enclave_t* enclave)
...
 
+    /* free allocate memory. */
+    result = _sgx_free_enclave_memory(enclave, enclave->size);
+
+done:
+
+    return result;
+}
+
+oe_result_t _sgx_free_enclave_memory(void* enclave, size_t size)
```
Comment (CodeMonkeyLeet) [inline host/sgxload.c]: Your use of this method is entirely inconsistent: `oe_sgx_create_enclave` calls this with a base address, but `oe_sgx_delete_enclave` calls this with an `oe_enclave_t*` and they are not interchangeable. Instead, define:

```c
oe_result_t _sgx_free_enclave_memory(void* addr, size_t size, bool is_simulation)
```

**Comment by sushantstripathi** [comment]
bors try

File: host/sgxload.c [hunk 4]
```diff
@@ -767,41 +732,48 @@ oe_result_t oe_sgx_delete_enclave(oe_enclave_t* enclave)
...
-        VirtualFree((void*)enclave->addr, 0, MEM_RELEASE);
-    else
-        VirtualFree((void*)enclave->addr, enclave->size, MEM_DECOMMIT);
-
+    VirtualFree((void*)addr, 0, MEM_RELEASE);
 #endif
 
     result = OE_OK;
-
-done:
```
Comment (CodeMonkeyLeet) [inline host/sgxload.c]: Why was this moved? We would like to explicitly avoid multiple exits in the routine.

```c
oe_result_t _sgx_free_enclave_memory(
    void* addr,
    size_t size,
    bool is_simulation)
{
    oe_result_t result = OE_UNEXPECTED;

#if defined(__linux__)

#if defined(OE_USE_LIBSGX)
    if (!is_simulation)
    {
        uint32_t enclave_error = 0;
        if (!enclave_delete(addr, &enclave_error))
            OE_RAISE(OE_PLATFORM_ERROR);
        if (enclave_error != 0)
            OE_RAISE(OE_PLATFORM_ERROR);
    }
    else /* FLC simulation mode needs to munmap. */
#endif
    {
        munmap(addr, size);
    }

#elif defined(_WIN32)
    VirtualFree(addr, 0, MEM_RELEASE);
#endif

    result = OE_OK;

done:
    return result;
}
```

Comment (CodeMonkeyLeet) [reply host/sgxload.c]: If that's the case, then I would simplify the return structure to avoid using error codes directly:
```c
oe_result_t _sgx_free_enclave_memory(
    void* addr,
    size_t size,
    bool is_simulation)
{
#if defined(__linux__)

#if defined(OE_USE_LIBSGX)
    if (!is_simulation)
    {
        uint32_t enclave_error = 0;
        if (!enclave_delete(addr, &enclave_error) ||
            enclave_error != 0)
            return OE_PLATFORM_ERROR;
    }
    else /* FLC simulation mode needs to munmap. */
#endif
    {
        munmap(addr, size);
    }

#elif defined(_WIN32)
    VirtualFree(addr, 0, MEM_RELEASE);
#endif

    return OE_OK;
}
```
